# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: FamatechCorp.AdvancedPortScanner
PackageVersion: 2.5.3869
PackageLocale: en-US
Publisher: Famatech Corp.
PackageName: Advanced Port Scanner
License: Open License
Copyright: Copyright © 2002-2019 Famatech Corp. and its licensors.  All rights reserved.
ShortDescription: Advanced Port Scanner Setup
ManifestType: defaultLocale
ManifestVersion: 1.2.0

