# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.2.0.schema.json

PackageIdentifier: FamatechCorp.AdvancedPortScanner
PackageVersion: 2.5.3869
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.2.0

